site_name: BaseModelIO

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_section_style: list
          members_order: source
          show_root_heading: true
          show_source: false
          show_signature_annotations: true

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - python