name: CI

on:
  pull_request:
    branches: ['main']
    paths-ignore: ['docs/**']
  push:
    branches: ['main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: read

jobs:

  linttype:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
      - name: Install all dependency groups
        run: pdm install -G linting -G typechecking -G dev

      - name: Run Tests
        run: |
          pdm run check

  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
      - name: Install all dependency groups
        run: pdm install

      - name: Run Tests
        run: |
          pdm run pytest
